name: momentum
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  flutter_facebook_auth: ^7.1.0
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/Widgets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
